{
    "hello_message": "안녕하세요",
    "goodbye_message": "안녕히 가세요",
    "search": "수색",
    "login": "로그인",
    "mydownloads": "내 다운로드",
    "my_lists": "내 목록",
    "all_music": "모든 노래",
    "settings": "설정",
    "hits": "조회수",
    "menu": "메뉴",
    "mymusic": "내 음악",
    "oldsearches": "이전 검색",
    "popular": "인기있는",
    "sign_in": "로그인",
    "username": "사용자 이름",
    "password": "암호",
    "add_user": "사용자 추가",
    "email": "이메일",
    "register": "회원 가입",
    "required_field": "필수 필드",
    "invalid_field": "잘못된 필드",
    "short": "짧은",
    "invalid": "잘못된",
    "not_found": "찾을 수 없음",
    "user": "사용자",
    "registered_mail": "등록 된 메일",
    "success": "성공",
    "exit": "출구",
    "internet_error": "인터넷 연결을 확인합니다.",
    "skip": "건너 뛰기",
    "next": "다음",
    "back": "백",
    "download_directory": "다운로드 디렉토리",
    "error": "오류",
    "please_wait": "기다려주십시오",
    "searching": "수색",
    "songname": "songName으로",
    "duration": "지속",
    "click_message": "듣기 또는 다운로드 터치",
    "my_melody": "내 멜로디",
    "listen_to_song": "노래 듣기",
    "data_scanned": "데이터를 스캔",
    "filenotopened": "파일을 열 수 없습니다",
    "ringtone_setf": "벨소리로 설정된",
    "ringtone_not_set": "벨소리 설정하지",
    "ringtone_set": "설정 벨소리",
    "play": "놀이",
    "download": "다운로드",
    "change_language": "언어 변경",
    "directory": "디렉토리",
    "change": "변화",
    "access_filesystem": "액세스 파일 시스템 ..",
    "one_level_up": "한 수준 위로",
    "_new": "새로운",
    "download_error": "다운로드 오류",
    "try_again": "다시 시도",
    "message": "메시지",
    "download_ringtone": "벨소리를 다운로드하세요",
    "ringtone_dowloading": "벨소리 dowloading",
    "clik_to_exit_message": "종료하려면 다시 클릭합니다.",
    "open_mp3_player": "MP3 플레이어로 열기",
    "setup_aimp": "AIMP MP3 플레이어 프로그램을 설치하시기 바랍니다"
}
